spring:
#数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.11.129:3306/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Lpy123456#
#jpa配置
  jpa:
    show-sql: true

#  对json对象里的NULL值做特殊处理
  jackson:
    default-property-inclusion: non_null

#设置访问根路径
server:
  servlet:
    context-path: /sell

#配置简单log日志
#logging:
#  pattern:
#    console: "$d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    root: debug

#微信参数配置
wechat:
#授权使用
  mpAppId: wxff4cc3ad51490418
  mpAppSecret: 2e8a6139ffb8cb348e2c7cdb25877bea
#支付使用
#  mpAppId: wxd898fcb01713c658
#  mchId: 1483469312
#  mchKey: C5245D70627C1F8E9964D494B0735025
#  keyPath: /var/weixin_cert/h5.p12
#  notifyUrl: http://birdsell.mynatapp.cc/sell/pay/notify