spring:
#数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.11.129:3306/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Lpy123456#
#  对json对象里的NULL值做特殊处理
  jackson:
    default-property-inclusion: non_null
#redis配置
  redis:
    host: 192.168.11.137
    port: 6379

#设置访问根路径
server:
  servlet:
    context-path: /sell

#微信参数配置
wechat:
#授权使用
  mpAppId: wxff4cc3ad51490418
  mpAppSecret: 2e8a6139ffb8cb348e2c7cdb25877bea
#支付使用
#  mpAppId: wxd898fcb01713c658
#  mchId: 1483469312
#  openAppId: wx6ad144e54af67d87
#  openAppSecret: 91a2ff6d38a2bbccfb7e9xxxxxx
#  mchKey: C5245D70627C1F8E9964D494B0735025
#  keyPath: /var/weixin_cert/h5.p12
#  notifyUrl: http://birdsell.mynatapp.cc/sell/pay/notify
  templateId:
    orderStatus: LDxXpeSkpGwkjk5BqqX7siMBLZF_pY5FBrcfnOq4i5E

project-url:
  wechatMpAuthorize: http://birdsell.mynatapp.cc
  wechatOpenAuthorize: http://birdsell.mynatapp.cc
  sell: http://birdsell.mynatapp.cc
logging:
  level:
    com.lpy.entity.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml