spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.11.119:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
#配置简单log日志
#logging:
#  pattern:
#    console: "$d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    root: debug

wechat:
  mpAppId: wxff4cc3ad51490418
  mpAppSecret: 2e8a6139ffb8cb348e2c7cdb25877bea